version: '3.8'
services:
  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - demo-network

  db:
    image: mysql
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: db
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      timeout: 30s
      interval: 5s
      retries: 5
    ports:
      - 3306:3306
    networks:
      - demo-network

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000" 
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin  
    volumes:
      - grafana_data:/var/lib/grafana  
    depends_on:
      - db
    networks:
      - demo-network

volumes:
  grafana_data:

networks:
  demo-network:
    driver: bridge
